service/apps/examples/urls.py
from django.urls import path
from django.views.generic import TemplateView

from apps.examples import views

app_name = 'examples'

urlpatterns = [
    path('', TemplateView.as_view(template_name='examples/index.html'), name='index'),
    path('cached/', views.CachedTemplateView.as_view(), name='cached'),
    path('tasks/', TemplateView.as_view(template_name='examples/tasks.html'), name='tasks'),
    path('api/tasks/', views.example_tasks, name='api_task_ids'),
    path('api/tasks/<int:pk>/', views.example_task_detailed, name='api_task'),
    path('api/tasks/create/', views.example_task_create, name='api_create_task'),
    path('api/tasks/delete/<int:pk>/', views.example_task_delete, name='api_delete_task'),
]

service/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from health_check import urls as health_urls

urlpatterns = [
    path('health/', include(health_urls)),

    path('admin/doc/', include(admindocs_urls)),
    path('admin/', admin.site.urls),

    path('robots.txt', TemplateView.as_view(
        template_name='txt/robots.txt',
        content_type='text/plain',
    )),
    path('humans.txt', TemplateView.as_view(
        template_name='txt/humans.txt',
        content_type='text/plain',
    )),
]

if settings.DEBUG:
    import debug_toolbar  # noqa: WPS433

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', RedirectView.as_view(permanent=True, pattern_name='examples:index')),
    path('examples/', include('apps.examples.urls')),
    *urlpatterns,
]

service/apps/examples/models.py
from django.db import models

MAX_TITLE_LENGTH = 256
MAX_DESCRIPTION_LENGTH = 1024
MAX_CATEGORY_LENGTH = 128


class ExampleCached(models.Model):
    title = models.CharField(max_length=MAX_TITLE_LENGTH)
    description = models.CharField(max_length=MAX_DESCRIPTION_LENGTH)
    category = models.CharField(max_length=MAX_CATEGORY_LENGTH)
    photo_url = models.URLField()
    content_text = models.TextField()
    content_html = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Data for cache'
        verbose_name_plural = 'Data for cache'

    def __str__(self):
        return 'Data for cache (user post) #{pk}'.format(pk=self.pk)


class ExampleAsyncTask(models.Model):
    percentage = models.PositiveIntegerField(default=0)
    one_percent_delay_milliseconds = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'Async task'
        verbose_name_plural = 'Async tasks'

    def __str__(self):
        return 'Async task #{pk} ({percentage}%)'.format(pk=self.pk, percentage=self.percentage)

service/apps/examples/views.py
import json
from http import HTTPStatus
from typing import Any, Dict

from django.conf import settings
from django.core.cache import cache
from django.core.exceptions import BadRequest
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView

from apps.examples.models import ExampleCached
from apps.examples.services import (
    create_example_async_task,
    delete_example_async_task,
    get_detailed_example_async_task,
    get_list_of_example_async_task_ids,
)


class CachedTemplateView(ListView):
    template_name = 'examples/cached.html'
    queryset: QuerySet = ExampleCached.objects.all()
    allow_empty = True

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        queryset: QuerySet = context_data['object_list']
        cache_key: str = str(queryset.query)
        cached_data = cache.get(cache_key, None)

        if cached_data:
            context_data['object_list'] = cached_data
            return context_data

        queryset_data = list(queryset)
        cache.set(
            cache_key,
            queryset_data,
            settings.REDIS_CACHE_DB_TTL,  # type: ignore
        )
        context_data['object_list'] = queryset_data

        return context_data


@require_http_methods(['GET'])
def example_tasks(request: HttpRequest) -> JsonResponse:
    data_ids = get_list_of_example_async_task_ids()
    return JsonResponse(data_ids, safe=False)


@require_http_methods(['GET'])
def example_task_detailed(request: HttpRequest, pk: int) -> JsonResponse:
    data_detailed = get_detailed_example_async_task(pk)

    if data_detailed is None:
        return JsonResponse({'error': 'Not found'})

    return JsonResponse(data_detailed)


@require_http_methods(['POST'])
def example_task_create(request: HttpRequest) -> JsonResponse:
    try:
        json_post_body: Dict[str, Any] = json.loads(request.body)
        one_percent_delay_milliseconds = int(json_post_body['one_percent_delay_milliseconds'])
    except (ValueError, KeyError, json.JSONDecodeError) as exception:
        raise BadRequest(str(exception))

    new_task_pk = create_example_async_task(one_percent_delay_milliseconds)

    return JsonResponse({'pk': new_task_pk})


@require_http_methods(['DELETE'])
def example_task_delete(request: HttpRequest, pk: int):
    delete_example_async_task(pk)
    return HttpResponse(status=HTTPStatus.OK)

service/apps/examples/templates/examples/cached.html
{% extends "admin/base.html" %}
{% block branding %}
    <h1 id="site-name"><a href="{% url 'examples:cached' %}">Пример кэширования кверисета</a></h1>
    {% if user.is_anonymous %}
        {% include "admin/color_theme_toggle.html" %}
    {% endif %}
{% endblock %}
{% block title %}Cached queryset example{% endblock %}
{% block pretitle %}(смотри метрики в DjDT, кэш живет всего минуту)
    <a href="{% url 'examples:index' %}">Вернуться к примерам</a>
    <p>
        Тут представлен для ознакомления пример кэширования кверисета.
        В следующий примерах кэшироваться будут данные, которые отдаются вьюшками drf.
    </p>
    <p>
        Как сделано сейчас делать не надо))) Кэшировать следует отрендеренную шаблонизатором страницу,
        или готовый json в виде строки. Для этого есть специальный декоратор:
    </p>
    <p>
        @cache_page(ttl).
    </p>
    <p>
        Для вьюшек, построенных на классах, он используется так:
    </p>
    <p>
        ...<br>
        @method_decorator(cache_page(60*60*2))<br>
        def get(...
    </p>
    <p>
        Подробнее для drf - <a href="https://www.django-rest-framework.org/api-guide/caching/">здесь</a>
    </p>
    <p>
        Цель этого примера - показать больший контроль над кэшированием,
        откуда брать уникальный ключ кэша,
        что набор данных уникален для строки sql запроса.
    </p>
{% endblock %}
{% block content_title %}<h1>Кэширование кверисета</h1>{% endblock %}
{% block content_subtitle %}<h2>Пример кэшированных данных</h2>{% endblock %}
{% block content %}
    <div id="content-main">
        <div class="module">
            {% for item in object_list %}
                <h2>{{ item.title }}</h2>
                <p>{{ item.content_text }}</p>
                <div>{{ item.content_html|safe }}</div>
                <img src="{{ item.photo_url }}">
            {% endfor %}
        </div>
    </div>
{% endblock %}

service/apps/examples/templates/examples/index.html
{% extends "admin/base.html" %}
{% block branding %}
    <h1 id="site-name"><a href="{% url 'admin:index' %}">Войти в админку</a></h1>
    {% if user.is_anonymous %}
        {% include "admin/color_theme_toggle.html" %}
    {% endif %}
{% endblock %}
{% block title %}Django linters formatters template{% endblock %}
{% block pretitle %}(роуты){% endblock %}
{% block content_title %}<h1>Шаблон Django приложения</h1>{% endblock %}
{% block content_subtitle %}<h2>Добавленные роуты и сторонние приложения</h2>{% endblock %}
{% block content %}
    <div id="content-main">
        <div class="module">
            <table>
                <caption>
                    <a href="{{ app.app_url }}" class="section" title="Добавленные Роуты шаблона - донора">Добавленные
                        Роуты шаблона - донора</a>
                </caption>
                <tr>
                    <th scope="row">
                        <a href="{% url 'admin:index' %}">{% url 'admin:index' %}</a>
                    </th>
                    <td>Админка</td>
                    <td><a href="https://docs.djangoproject.com/en/4.2/ref/contrib/admin/">django.admin.contrib</a></td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="{% url 'django-admindocs-docroot' %}">{% url 'django-admindocs-docroot' %}</a>
                    </th>
                    <td>Самогенерирующаяся дока</td>
                    <td>
                        <a
                            href="https://docs.djangoproject.com/en/4.2/ref/contrib/admin/admindocs/"
                        >
                            django.contrib.admindocs
                        </a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="/admin/axes/">/admin/axes/</a>
                    </th>
                    <td>Защита от brute-force и ddos</td>
                    <td><a href="https://django-axes.readthedocs.io/en/latest/">axes</a></td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="/robots.txt">/robots.txt</a>
                    </th>
                    <td>мета информация для поисковиков</td>
                    <td><a href="https://developer.mozilla.org/en-US/docs/Glossary/Robots.txt">MDN docs</a></td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="/humans.txt">/humans.txt</a>
                    </th>
                    <td>мета информация об авторах/владельцах</td>
                    <td><a href="https://humanstxt.org/">humanstxt.org</a></td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="/health/">/health/</a>
                    </th>
                    <td>Проверка работоспособности, выявление проблем</td>
                    <td><a href="https://django-health-check.readthedocs.io/en/latest/">django-health-check</a></td>
                </tr>
                <tr>
                    <th scope="row">
                        DjDT (смотри правый верхний угол сайта)
                    </th>
                    <td>Отладочный туллбар для джанги с кучей интересных метрик</td>
                    <td><a href="https://django-debug-toolbar.readthedocs.io/en/latest/">django-debug-toolbar</a></td>
                </tr>
            </table>
        </div>

        <div class="module">
            <table>
                <caption>
                    <a href="{{ app.app_url }}" class="section" title="Добавленные Роуты">Добавленные Роуты</a>
                </caption>
                <tr>
                    <th scope="row">
                        <a href="{% url "examples:cached" %}">{% url "examples:cached" %}</a>
                    </th>
                    <td>Пример работы кэша кверисетов.
                    </td>
                    <td><a href="{% url "examples:cached" %}">Дока там-же где и пример</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="/admin/redisboard/redisserver/">/admin/redisboard/redisserver/</a>
                    </th>
                    <td>Управление и анализ работы redis в админке. Там сейчас подключено 2 БД redis (Кэш и очередь для
                        celery)
                    </td>
                    <td>
                        <a href="https://django-redisboard.readthedocs.io/en/latest/">
                            django-redisboard
                        </a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="{% url "examples:tasks" %}">{% url "examples:tasks" %}</a>
                    </th>
                    <td>Пример работы асинхронных задач
                    </td>
                    <td><a href="{% url "examples:tasks" %}">Дока там-же где и пример</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <a href="http://localhost:5555/" target="_blank">http://localhost:5555/</a>
                    </th>
                    <td>Средство администрирования celery</td>
                    <td>
                        <a href="https://flower.readthedocs.io/en/latest/">
                            flower
                        </a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

service/apps/examples/templates/examples/tasks.html
{% extends "admin/base.html" %}
{% block branding %}
    <h1 id="site-name"><a href="{% url 'examples:cached' %}">Пример асинхронных задач</a></h1>
    {% if user.is_anonymous %}
        {% include "admin/color_theme_toggle.html" %}
    {% endif %}
{% endblock %}
{% block title %}Async tasks example{% endblock %}
{% block pretitle %}
    <a href="{% url 'examples:index' %}">Вернуться к примерам</a>
    <p>
        <b>Celery</b> это распределенная очередь задач, которая выполняется параллельно с основной программой django.
        При этом ей доступно все окружение проекта, например база данных
    </p>
    <p>
        <b>Celery</b> для выполнения асинхронных задач использует воркеры - это отдельные контейнеры,
        внутри которых выполняются задачи. Воркеров может быть сколько угодно, насколько хватит ресурсов.
        В этом проекте 1 воркер.
    </p>
    <p>
        <b>Celery</b> для работы нужен брокер сообщений. В данном проекте, в качестве брокера используется redis
    </p>
{% endblock %}
{% block content_title %}<h1>Асинхронные таски</h1>{% endblock %}
{% block content_subtitle %}<h2>Пример асинхронных тасков</h2>{% endblock %}
{% block content %}
    <div id="content-main">
        <form class="form-create">
            <p>
                <label>
                    Имитация полезного действия на сервере в миллисекундах:
                    <input type="number" max="1000" min="100" value="300" name="one_percent_delay_milliseconds">
                </label>
            </p>
            <p><input type="submit" value="Создать задачу"></p>
        </form>
        <div class="module">
            <table class="tasks-container">
                <caption>
                    <a href="{{ app.app_url }}" class="section" title="Добавленные Роуты">Живые таски</a>
                </caption>
            </table>

        </div>
    </div>

    <script nonce="dev">
        const tasks = {}

        async function fetchTaskIds() {
            const response = await fetch("{% url "examples:api_task_ids" %}", {method: "GET"});
            return await response.json();
        }

        async function fetchTask(pk) {
            const response = await fetch("{% url "examples:api_task" 0 %}".replace("0", pk), {method: "GET"})
            return await response.json()
        }

        async function fetchCreateTask(one_percent_delay_milliseconds, csrfToken) {
            const response = await fetch(
                "{% url "examples:api_create_task" %}",
                {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": csrfToken,
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify({
                        one_percent_delay_milliseconds,
                    }),
                    credentials: 'same-origin',
                },
            );
            return await response.json();
        }

        async function fetchDeleteTask(pk, csrfToken) {
            const response = await fetch(
                "{% url "examples:api_delete_task" 0 %}".replace("0", pk),
                {
                    method: "DELETE",
                    headers: {
                        "X-CSRFToken": csrfToken,
                        "Content-Type": "application/json",
                    },
                    credentials: "same-origin",
                },
            );
            return response.status === 200 ? {status: "ok"} : {status: "skipped"};
        }

        function isTaskExist(id) {
            return id in tasks;
        }

        function getExcludedIDs(fetchedIDs) {
            const existIDsSet = new Set(Object.keys(tasks));
            for (let item of fetchedIDs) {
                existIDsSet.delete(item.toString());
            }
            return Array.from(existIDsSet);
        }

        function createTaskDOMElement(id, csrfToken) {
            const tr = document.createElement('tr');
            tr.dataset.id = id;

            const rowHeader = document.createElement('th');
            rowHeader.setAttribute('scope', 'row');
            const rowHeaderText = document.createTextNode(`Task ID: ${id}`);

            const rowMiddle = document.createElement('td');
            const rowMiddleProgress = document.createElement('progress');
            rowMiddleProgress.setAttribute('min', '0');
            rowMiddleProgress.setAttribute('max', '100');
            rowMiddleProgress.setAttribute('value', '0');

            const rowLast = document.createElement('td');
            const rowLastButton = document.createElement('button')
            const rowLastButtonText = document.createTextNode('Удалить');

            tr.appendChild(rowHeader);
            tr.appendChild(rowMiddle);
            tr.appendChild(rowLast);

            rowHeader.appendChild(rowHeaderText);
            rowMiddle.appendChild(rowMiddleProgress);
            rowLast.appendChild(rowLastButton);
            rowLastButton.appendChild(rowLastButtonText);

            rowLastButton.addEventListener('click', (event) => {
                event.preventDefault();
                fetchDeleteTask(id, csrfToken).then(() => {
                    console.info(`Task ID${id} was deleted`)
                })
            })

            const timerID = setInterval(async () => {
                const data = await fetchTask(id);
                const {percentage} = data;
                if (Number(percentage) === 100)
                    clearInterval(timerID)
                rowMiddleProgress.setAttribute('value', percentage);
            }, 300);

            return {element: tr, timerID};
        }

        function addTask(id, container, csrfToken) {
            const {element, timerID} = createTaskDOMElement(id, csrfToken)
            tasks[id] = {
                element,
                timerID,
            };
            container.appendChild(element);
        }

        function deleteTask(id, container) {
            const {element, timerID} = tasks[id];
            clearInterval(timerID);
            container.removeChild(element);
            delete tasks[id];
        }

        document.addEventListener('DOMContentLoaded', () => {
            const contentMain = document.getElementById("content-main");
            const formCreate = contentMain.querySelector(".form-create");
            const tasksContainer = contentMain.querySelector('.tasks-container')
            const csrfToken = "{{ csrf_token }}"

            formCreate.addEventListener('submit', (event) => {
                event.preventDefault();
                const formData = new FormData(formCreate);
                const one_percent_delay_milliseconds = formData.get('one_percent_delay_milliseconds')
                fetchCreateTask(one_percent_delay_milliseconds, csrfToken).then(data => {
                    const {pk} = data;
                    console.info(`Task ID${pk} was created`);
                })
            })

            setInterval(async () => {
                const ids = await fetchTaskIds();
                ids.forEach(id => {
                    if (!isTaskExist(id)) {
                        addTask(id, tasksContainer, csrfToken);
                    }
                })
                const excludedIDs = getExcludedIDs(ids);
                excludedIDs.forEach(id => {
                    deleteTask(id, tasksContainer)
                })
            }, 500)

        })
    </script>
{% endblock %}